# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-12-01 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifCode',
            new_name='VerifyCode',
        ),
    ]
